[package]
name = "site"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
sycamore = "0.9.1"
web-sys = { version = "0.3.77", features = [ "CssStyleDeclaration", "DomRect", "Element" ] }
